name = "HStools"
uuid = "c0d85d9b-15d7-40ff-901a-6fa50c3b6795"
authors = ["Brian D. Klahn <briandk@virginia.edu> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.11"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
